// Layout
import Layout from "../layout/Layout";

export default function Home() {
  return (
    <Layout>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
      <h1>Inicio</h1>
    </Layout>
  );
}
